version: '3.7'

services:
    web:
        container_name: 'zespol-server-asp'
        image: 'aspnetcoreapp'
        build:
            context: .
            dockerfile: ./ZespolServer/server.windows.dockerfile
        ports:
            - "5000:80"
            - "5001:443"
        depends_on:
            - "postgres"
        networks:
            - main-net
    postgres:
        container_name: 'postgres'
        image: 'postgres'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        networks:
            - main-net

networks:
    main-net:
        driver: bridge