version: '3.7'

services:
  web:
    container_name: 'zespol-server-asp-linux'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: ./ZespolServer/server.linux.dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - "postgres"
    networks:
      - main-net
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/cert.pfx
    volumes:
      - ./cert.pfx:/certs/cert.pfx
  postgres:
    container_name: 'zespol-postgres-linux'
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - main-net

networks:
  main-net:
    driver: bridge